# Generated by Django 3.1.3 on 2020-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_item',
            name='id',
        ),
        migrations.AddField(
            model_name='todo_item',
            name='todo_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
