# Generated by Django 3.1.3 on 2020-12-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201206_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='todo_auth',
            field=models.CharField(default='rafa', max_length=30),
            preserve_default=False,
        ),
    ]
