# Generated by Django 3.1.3 on 2020-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_item_todo_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='required_time',
            field=models.IntegerField(default=1),
        ),
    ]
