# Generated by Django 3.1.3 on 2020-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_item_required_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('o', 'ongoing'), ('d', 'done'), ('nd', 'not_doing'), ('h', 'hidden')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo_item',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo_item',
            name='importance',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
