# Generated by Django 3.1.3 on 2021-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicjas_paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='painting_dimensions',
            field=models.CharField(default='100x300', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='upload',
            field=models.FileField(upload_to='static/ap/uploads/'),
        ),
    ]
