# Generated by Django 3.1.3 on 2021-01-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alicjas_paintings', '0002_auto_20210105_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/ap/uploads/')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alicjas_paintings.painting')),
            ],
        ),
    ]
