# Generated by Django 3.1.3 on 2021-02-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alicjas_paintings', '0006_cart_items_painting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_items',
            name='painting_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alicjas_paintings.painting'),
            preserve_default=False,
        ),
    ]
