# Generated by Django 3.1.3 on 2021-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicjas_paintings', '0007_favorite_items_painting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='image',
            field=models.ImageField(upload_to='media/ap/uploads/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='upload',
            field=models.FileField(upload_to='media/ap/uploads/'),
        ),
    ]
